### ISSUE TITLE
Scandio.wait promises don't return "this"

### ISSUE THREAD

**Issue by ataraxie** [scandio/scandiojs#14]
core.js => Scandio.wait
```
return {
 done: function(fn) {
    callbacks.done = fn;
 },
 fail: function(fn) {
    callbacks.fail = fn;
 }
};
```

Currently I'll have to call it like this:
```
var promise = Scandio.wait(...);
promise.done = function() {};
promise.fail = function() {};
```

I can't call it in a chained manner since done/fail don't return anything:
```
Scandio.wait(...).done(...).fail(...)
```

I guess done and fail in the promise object could simply return `this`? @tdeekens

**Comment by tdeekens** [comment]
Chaing :heart:! Erm, I guess one would have to call `new waitFn({` in https://github.com/scandio/scandiojs/blob/master/js/core.js#L124 too to get a this with the function contructor, right?

**Comment by ataraxie** [comment]
Uah, a function constructor :scream: Why can we not return this in the done and fail methods?

**Comment by tdeekens** [comment]
...the question is what `this` is as we never invoked the `new` on anything I guess it's the lovely `window`.

**Comment by ataraxie** [comment]
I think you're wrong. When I call `Scandio.wait(...).done(...).fail(...)`, wait returns the object on which done is defined. Done does so as well. And fail, too. It will always be the object { done: ..., fail: ...}

I just tested this:
```
return {
   done: function(fn) {
      callbacks.done = fn;
      return this;
   },
   fail: function(fn) {
      callbacks.fail = fn;
      return this;
   }
};
```

Try it yourself:
```
Scandio.wait({
	condition: function() {
		return false;
	}
}).done(function() {
	console.log("Done, Tobi!!");
}).fail(function() {
	console.log("Fail, Tobi!!");
});
```

**Comment by tdeekens** [comment]
True dat :clap: it's cause we create a new instance of scandiojs in the [intro.js](https://github.com/scandio/scandiojs/blob/master/js/intro.js#L74) file.

So just make it return this and it's all good? :sparkles:
