### ISSUE TITLE
Scandio.module ready function loses "this" context

### ISSUE THREAD

**Issue by ataraxie** [scandio/scandiojs#15]
In the given document.ready function, this will refer to the returned object in the Scandio module and thus throw errors:
```
modEnv.readyFn(invokedModule.ready);
```

The given function should be called with the original context object of the ready function as "this"

**Comment by tdeekens** [comment]
...so a `.call` does the trick?

**Comment by ataraxie** [comment]
Dann müsste ja irgendwie übergeben werden was das ```this``` werden soll. Da das ja quasi im Moment die zentrale Funktion von ScandioJS ist, finde ich das nicht besonders schön. Ist zu low-level. Ich weiß gerade auch nicht wie man das vernünftig macht. Ich bin auch inzwischen allgemein über den Nutzen der DOMReady Verwaltung unschlüssig. Ich sehe nicht mehr den großen Vorteil gegenüber einfach $(document).ready zu nutzen. Wie siehst du das?

**Comment by tdeekens** [comment]
`this` übergeben finde ich irgendwie lahm. Das führt als Pattern immer zu übelster Verwirrung weil keiner mehr blickt was der Kontext von irgendwas ist wenn man drauf schaut.

Ich würde auch sagen, dass einfach `$(document).ready` benutzt wird - ich glaube nicht, dass irgendwer seine eigene readyFn schreiben will. War das Feature nicht irgendwie eine Notwendigkeit aus Confluence.

**Comment by ataraxie** [comment]
Alle Atlassian Sachen haben ihr ```AJS.toInit``` (AJS ist "Atlassian JavaScript"), was wiederum dann selbst ```$(document).ready``` aufruft. Wir übergeben quasi immer ```{ readyFn: AJS.toInit }```. Ich hatte das damals so gemacht, weil ich dachte es ist sinnvoll wenn ScandioJS die ganzen DOMReady listeners verwaltet. Quasi um mehr Kontrolle zu haben. Aber inzwischen empfinde ich das als ziemlichen Overhead.

**Comment by tdeekens** [comment]
...ich erinnere mich. Aber sollte nicht jede readyFn, egal aus welcher Library sie kommt, zum gleichen Zeitpunkt feuern? DOM-Ready ist ja nunmal 'ne ziemlich klare Ansage. Es sei denn AJS initialisiert noch nach dem DOM-Ready irgendwas und feuert dann die Listener ab.

**Comment by ataraxie** [comment]
Hmm. Ja klar, das Event fliegt immer zum gleichen Zeitpunkt. Es könnte halt sein dass noch irgendwas mit der Reihenfolge gemacht wird. Normal werden die Listener ja in der Reihenfolge abgearbeitet wie sie gesetzt worden sind. Wenn man daran jetzt irgendwann was ändern wollen würde, dann bräuchte man eine eigene Verwaltung. Die wir mit dem derzeitigen Pattern jetzt haben. Wobei man da wahrscheinlich auch irgendwie anders eingreifen könnte. Ich weiß auch nicht ob man das irgendwann mal machen wollen würde...

**Comment by tdeekens** [comment]
...aber die Reihenfolge würde doch auch eventuell bei `$(document).ready` beibehalten? Man könnte das doch auch noch mal eintüten indem ScandioJS selbst auf das ready intern hört und dann einen Listener nach dem anderen reinsteckt. Wenn man da bei der Reihenfolge bange ist?

**Comment by tdeekens** [comment]
...wät tun wie denn mit dem Spass hier?

**Comment by ataraxie** [comment]
Ja, das ist etwas doof. Ich bin relativ sicher, dass wir dieses DOMReady Handling komplett rausschmeißen sollen, und die Leute ihre Listener stattdessen selber machen wie sie Bock haben. Das dumme ist jetzt halt dass wir das rückwärts-kompatibel halten müssen. Also eigentlich müssten wir das ganze readyFn Dingens irgendwie deprecated machen. Wie macht man sowas denn in der JS-Welt?

**Comment by tdeekens** [comment]
...ich würde 'ne nen `console.warn` bei jedem Aufruf machen. Also jedes mal bei der Mitgabe einer `readyFn`. Dabei markieren wir es als depricated und für den Rest gibt es Semver. Irgendwann machen wir dann bumpen wir Major und damit ist das Thema durch. Wir zwingen schließlich keinen per Bower latest zu ziehen.

**Comment by ataraxie** [comment]
Klingt vernünftig! Willst du das warn einbauen? Kann sonst auch ich machen.

**Comment by tdeekens** [comment]
Mach ich bald.

**Comment by tdeekens** [comment]
...hier der Link direkt ins change set https://github.com/scandio/scandiojs/commit/4cf019355b2b45cded53bfbd0c922df81e3e89dc#diff-d85c7ecdc144ac4aec3ee7a0b24c3f9fR53
