### ISSUE TITLE
Modules currently MUST return an object

### ISSUE THREAD

**Issue by ataraxie** [scandio/scandiojs#16]
Otherwise invokedModule will be undefined here:
```
Scandio.isFunction(invokedModule.ready)
```
Check if invokedModule is defined before calling this!

**Comment by tdeekens** [comment]
:confused: :question:

**Comment by ataraxie** [comment]
If you do this:
```
Scandio.module('XXX', function() {
   // code but no return object
});
```
The ```invokedModule``` variable will be undefined. But not every module needs an "interface" object (meaning everything is private).

**Comment by tdeekens** [comment]
...so internally wrapping the function and then passing it down would fix things?

**Comment by ataraxie** [comment]
Hmm. Not sure what you mean. I just thought about something like this:
```
Scandio.isObject(invokedModule) && Scandio.isFunction(invokedModule.ready)
```

**Comment by tdeekens** [comment]
Jupsa, entweder so oder du machst sowas wie:

```javascript
if (!Scandio.isObject(invokedModule) { 
  invokedModule = {
     ready: invokedModule
  }
}
```

oder ich verstehe gerade alles falsch. Macht aber nichts. Deine Lösung ist eh kürzer! :star2:

**Comment by ataraxie** [comment]
Ehm. ```ready``` muss ne Funktion sein. Ist quasi der DOMReady listener der über Scandio registriert wurde (statt einfach mit ```$(document).ready``` oder so). Kurzum: wenn's kein ```invokedModule``` gibt, dann will ich auch nix machen ;)

**Comment by tdeekens** [comment]
Ai.
